name: Generate 3D Contribution Graph

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate 3D graph
        uses: Platane/snk@v3
        with:
          github_user_name: CENGTOKSOY
          outputs: |
            profile-3d-contrib/profile-night-view.svg

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "Update 3D contribution graph" || echo "No changes"
          git push
